// Generated by https://quicktype.io

export interface Posts {
    userId: number;
    id:     number;
    title:  string;
    body:   string;
}

export interface Data<T> {
    statusCode: number;
    message: string;
    data: T | Array<T>;
  }